import {
  AlignmentType,
  BorderStyle,
  Document,
  Footer,
  Header,
  Packer,
  PageNumber,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from 'docx'

const blankLine = '________________________________________'
const notice =
  'Template generated by Ophile. Review and approval may be required before use as a legally binding agreement.'

const colors = {
  navy: '1F4E78',
  blue: 'D9EAF7',
  paleBlue: 'F4F8FC',
  gray: 'F2F4F7',
  border: 'B8C4CE',
  text: '1F2937',
  muted: '667085',
  white: 'FFFFFF',
}

const unlimitedFields = {
  organizationAdminLimit: 'unlimitedOrganizationAdmins',
  helpDeskLimit: 'unlimitedHelpDesk',
  userLimit: 'unlimitedUsers',
  dailyTicketLimit: 'unlimitedDailyTickets',
}

const tableBorders = {
  top: { style: BorderStyle.SINGLE, size: 4, color: colors.border },
  bottom: { style: BorderStyle.SINGLE, size: 4, color: colors.border },
  left: { style: BorderStyle.SINGLE, size: 4, color: colors.border },
  right: { style: BorderStyle.SINGLE, size: 4, color: colors.border },
  insideHorizontal: {
    style: BorderStyle.SINGLE,
    size: 4,
    color: colors.border,
  },
  insideVertical: {
    style: BorderStyle.SINGLE,
    size: 4,
    color: colors.border,
  },
}

const noBorders = {
  top: { style: BorderStyle.NONE, size: 0, color: colors.white },
  bottom: { style: BorderStyle.NONE, size: 0, color: colors.white },
  left: { style: BorderStyle.NONE, size: 0, color: colors.white },
  right: { style: BorderStyle.NONE, size: 0, color: colors.white },
  insideHorizontal: {
    style: BorderStyle.NONE,
    size: 0,
    color: colors.white,
  },
  insideVertical: {
    style: BorderStyle.NONE,
    size: 0,
    color: colors.white,
  },
}

function formatDate(value) {
  if (!value) return blankLine
  return new Intl.DateTimeFormat('en', { dateStyle: 'long' }).format(
    new Date(`${value}T00:00:00`),
  )
}

function formatPeriod(value, unit) {
  if (!value || !unit) return blankLine
  const singular = Number(value) === 1
  const label =
    unit === 'YEARS'
      ? singular
        ? 'Year'
        : 'Years'
      : singular
        ? 'Month'
        : 'Months'
  return `${value} ${label}`
}

function formatFrequency(value) {
  const labels = {
    MONTHLY: 'Monthly',
    QUARTERLY: 'Quarterly',
    YEARLY: 'Yearly',
    ONE_TIME: 'One-Time',
  }
  return labels[value] ?? blankLine
}

function formatHosting(value) {
  if (value === 'CLOUD') return 'Cloud Hosted'
  if (value === 'ON_PREMISE') return 'On-Premise'
  return 'Not Applicable'
}

function formatLimit(features, key) {
  if (!features) return blankLine
  if (features[unlimitedFields[key]]) return 'Unlimited'
  return features[key] ?? blankLine
}

function paragraph(text, options = {}) {
  return new Paragraph({
    alignment: options.alignment,
    spacing: {
      before: options.before ?? 0,
      after: options.after ?? 120,
      line: options.line ?? 276,
    },
    children: [
      new TextRun({
        text: String(text),
        bold: options.bold,
        italics: options.italics,
        color: options.color ?? colors.text,
        size: options.size ?? 21,
        font: 'Aptos',
      }),
    ],
  })
}

function sectionHeading(number, title) {
  return new Paragraph({
    spacing: { before: 320, after: 160 },
    keepNext: true,
    border: {
      bottom: {
        style: BorderStyle.SINGLE,
        size: 8,
        color: colors.navy,
        space: 5,
      },
    },
    children: [
      new TextRun({
        text: `${number}. ${title}`,
        bold: true,
        color: colors.navy,
        size: 26,
        font: 'Aptos Display',
      }),
    ],
  })
}

function valueCell(value, options = {}) {
  return new TableCell({
    width: { size: options.width ?? 65, type: WidthType.PERCENTAGE },
    shading: { fill: options.fill ?? colors.white },
    margins: { top: 120, bottom: 120, left: 140, right: 140 },
    children: [paragraph(value, { bold: options.bold, after: 0 })],
  })
}

function labelCell(label) {
  return new TableCell({
    width: { size: 35, type: WidthType.PERCENTAGE },
    shading: { fill: colors.paleBlue },
    margins: { top: 120, bottom: 120, left: 140, right: 140 },
    children: [
      paragraph(label, { bold: true, color: colors.navy, after: 0 }),
    ],
  })
}

function termsTable(rows) {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    borders: tableBorders,
    rows: rows.map(
      ([label, value]) =>
        new TableRow({
          cantSplit: true,
          children: [labelCell(label), valueCell(value)],
        }),
    ),
  })
}

function signatureCell(title, company) {
  return new TableCell({
    width: { size: 50, type: WidthType.PERCENTAGE },
    margins: { top: 160, bottom: 160, left: 120, right: 240 },
    children: [
      paragraph(title, { bold: true, color: colors.navy, after: 220 }),
      paragraph(`Company: ${company}`, { after: 280 }),
      paragraph(`Representative Name: ${blankLine}`, { after: 280 }),
      paragraph(`Position: ${blankLine}`, { after: 280 }),
      paragraph(`Signature: ${blankLine}`, { after: 280 }),
      paragraph(`Date: ${blankLine}`, { after: 0 }),
    ],
  })
}

function createHeader() {
  return new Header({
    children: [
      new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        borders: noBorders,
        rows: [
          new TableRow({
            children: [
              new TableCell({
                width: { size: 50, type: WidthType.PERCENTAGE },
                children: [
                  paragraph('OPHILE', {
                    bold: true,
                    color: colors.navy,
                    size: 30,
                    after: 0,
                  }),
                ],
              }),
              new TableCell({
                width: { size: 50, type: WidthType.PERCENTAGE },
                children: [
                  paragraph('SUBSCRIPTION SERVICES', {
                    bold: true,
                    color: colors.muted,
                    size: 18,
                    alignment: AlignmentType.RIGHT,
                    after: 0,
                  }),
                ],
              }),
            ],
          }),
        ],
      }),
      new Paragraph({
        border: {
          bottom: {
            style: BorderStyle.SINGLE,
            size: 12,
            color: colors.navy,
            space: 3,
          },
        },
        children: [],
      }),
    ],
  })
}

function createFooter() {
  return new Footer({
    children: [
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { before: 100, after: 80 },
        children: [
          new TextRun({
            text: notice,
            italics: true,
            color: colors.muted,
            size: 15,
            font: 'Aptos',
          }),
        ],
      }),
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [
          new TextRun({
            children: ['Page ', PageNumber.CURRENT, ' of ', PageNumber.TOTAL_PAGES],
            color: colors.muted,
            size: 16,
            font: 'Aptos',
          }),
        ],
      }),
    ],
  })
}

function buildContractDocument(fields) {
  const children = [
    paragraph('SUBSCRIPTION NEGOTIATION AGREEMENT', {
      alignment: AlignmentType.CENTER,
      bold: true,
      color: colors.navy,
      size: 34,
      before: 120,
      after: 80,
    }),
    paragraph('Confidential Subscription Terms', {
      alignment: AlignmentType.CENTER,
      color: colors.muted,
      size: 20,
      after: 280,
    }),
    termsTable([
      ['Agreement Reference', fields.reference],
      ['Agreement Date', fields.agreementDate],
      ['Agreement Status', fields.status],
    ]),
    sectionHeading(1, 'PARTIES'),
    termsTable([
      ['Party A', 'Ophile'],
      ['Party B', fields.company],
    ]),
    paragraph(
      'The parties agree to establish the subscription terms recorded in this agreement. These terms describe the selected plan, service limits, contract period, and payment arrangement agreed for the Company.',
      { alignment: AlignmentType.JUSTIFIED, before: 160 },
    ),
    sectionHeading(2, 'SUBSCRIPTION PLAN'),
    termsTable([
      ['Selected / Negotiated Plan', fields.plan],
      ['Hosting Deployment', fields.hostingDeployment],
    ]),
    sectionHeading(3, 'AGREEMENT PERIOD'),
    termsTable([
      ['Subscription Start Date', fields.startDate],
      ['Contract Period', fields.period],
    ]),
    paragraph(
      'The agreement continues for the stated period unless it is amended or terminated according to terms documented and accepted by both parties.',
      { alignment: AlignmentType.JUSTIFIED, before: 160 },
    ),
    sectionHeading(4, 'SUBSCRIPTION FEATURES AND LIMITS'),
    termsTable([
      ['Organization Admin Limit', fields.organizationAdminLimit],
      ['Help Desk User Limit', fields.helpDeskLimit],
      ['Standard User Limit', fields.userLimit],
      ['Daily Ticket Limit', fields.dailyTicketLimit],
      ['Reports Access', fields.reportsAccess],
      ['Advanced Permission Matrix', fields.advancedPermissionMatrix],
    ]),
    sectionHeading(5, 'PAYMENT TERMS'),
    termsTable([
      ['Negotiated Subscription Amount', fields.payment],
      ['Billing Frequency', fields.billingFrequency],
      ['Payment Method', 'Card Payment'],
    ]),
    paragraph(
      'Payments made under this agreement must reference the applicable subscription and negotiation records maintained by Ophile. Payment processing details are managed separately from this agreement.',
      { alignment: AlignmentType.JUSTIFIED, before: 160 },
    ),
    sectionHeading(6, 'AGREEMENT AND AMENDMENTS'),
    paragraph(
      'Party A and Party B acknowledge that the subscription configuration, limits, price, and contract period recorded above represent the negotiated terms agreed between the parties.',
      { alignment: AlignmentType.JUSTIFIED },
    ),
    paragraph(
      'Any modification to these terms should be documented and accepted by both parties. This generated document does not replace any review or approval required by the parties.',
      { alignment: AlignmentType.JUSTIFIED },
    ),
    sectionHeading(7, 'SIGNATURES'),
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      borders: tableBorders,
      rows: [
        new TableRow({
          cantSplit: true,
          children: [
            signatureCell('PARTY A — OPHILE', 'Ophile'),
            signatureCell('PARTY B — COMPANY', fields.signatureCompany),
          ],
        }),
      ],
    }),
  ]

  return new Document({
    title: 'Ophile Subscription Negotiation Agreement',
    subject: 'Subscription negotiation and contract terms',
    creator: 'Ophile',
    description: notice,
    styles: {
      default: {
        document: {
          run: { font: 'Aptos', size: 21, color: colors.text },
          paragraph: { spacing: { line: 276, after: 120 } },
        },
      },
    },
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: 1080,
              right: 1080,
              bottom: 1260,
              left: 1080,
              header: 540,
              footer: 540,
            },
          },
        },
        headers: { default: createHeader() },
        footers: { default: createFooter() },
        children,
      },
    ],
  })
}

export function generateBlankContract() {
  return buildContractDocument({
    reference: blankLine,
    agreementDate: blankLine,
    status: blankLine,
    company: blankLine,
    plan: blankLine,
    startDate: blankLine,
    period: blankLine,
    organizationAdminLimit: blankLine,
    helpDeskLimit: blankLine,
    userLimit: blankLine,
    dailyTicketLimit: blankLine,
    reportsAccess: blankLine,
    advancedPermissionMatrix: blankLine,
    hostingDeployment: blankLine,
    payment: blankLine,
    billingFrequency: blankLine,
    signatureCompany: blankLine,
  })
}

export function generateNegotiationContract(negotiation, company) {
  return buildContractDocument({
    reference: negotiation.reference,
    agreementDate: formatDate(negotiation.createdAt.slice(0, 10)),
    status: negotiation.status,
    company: company.name,
    plan: negotiation.plan,
    startDate: formatDate(negotiation.startDate),
    period: formatPeriod(negotiation.periodValue, negotiation.periodUnit),
    organizationAdminLimit: formatLimit(
      negotiation.features,
      'organizationAdminLimit',
    ),
    helpDeskLimit: formatLimit(negotiation.features, 'helpDeskLimit'),
    userLimit: formatLimit(negotiation.features, 'userLimit'),
    dailyTicketLimit: formatLimit(
      negotiation.features,
      'dailyTicketLimit',
    ),
    reportsAccess: negotiation.features.reportsAccess ? 'Yes' : 'No',
    advancedPermissionMatrix: negotiation.features.advancedPermissionMatrix
      ? 'Available'
      : 'Not Available',
    hostingDeployment: formatHosting(negotiation.hostingDeployment),
    payment: `$${Number(negotiation.negotiatedAmount).toFixed(2)}`,
    billingFrequency: formatFrequency(negotiation.billingFrequency),
    signatureCompany: company.name,
  })
}

export async function downloadDocxFile(filename, document) {
  const blob = await Packer.toBlob(document)
  const url = URL.createObjectURL(blob)
  const link = window.document.createElement('a')
  link.href = url
  link.download = filename
  window.document.body.appendChild(link)
  link.click()
  link.remove()
  URL.revokeObjectURL(url)
}
